// grammar generated by SJTU acm

grammar Mx;

import Lexis;

// start parser
start
    : primaryExpression*
    | typeDeclaration*
    | function*
    ;

function : x;
typeDeclaration : x;

primaryExpression : x;

x : '1';